const colaboreDefault = ``
const voluntarioDefault =``
const voluntarioTipo1 = ``
const voluntarioTipo1Step1=``
const voluntarioTipo1Step2=``
const voluntarioTipo1Step3=``
const voluntarioTipo2 = ``
const voluntarioTipo2Step1 = ``
const voluntarioTipo2Step2 = ``
const voluntarioTipo2Step3 = ``
const doarDefault = ``
const doarTipo1 = ``
const doarTipo1Step1 = ``
const doarTipo1Step2 = ``
const doarTipo1Step3 = ``
const doarTipo2 = ``
const doarTipo2Step1 = ``
const doarTipo2Step2 = ``
const doarTipo2Step3 = ``