CREATE TABLE usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    nome_completo CHAR(900) NOT NULL,
    username VARCHAR(18) NOT NULL UNIQUE,
    is_active_user BLOB(1) DEFAULT 1,
    created_at VARCHAR(15) DEFAULT (DATETIME('now')),
    updated_at VARCHAR(15) DEFAULT (DATETIME('now'))
);

-- COMENTARIO DE ERRO: O ERRO ESTAVA HONESTAMENTE NÃO SEI AONDE, MAS ACREDITO QUE NO (DATETIME('NOW)) COM UM PARENTESIS A MENOS, AINDA ASSIM SEI QUE O TIPO DE DADO SERIA DATETIME MAS USANDO VARCHAR POR SE RECEBE DADOS EM ISOSTRING
ALTER TABLE usuarios ADD COLUMN password_hash  VARCHAR(120) NOT NULL  ;
-- COMENTARIO SOBRE A PROXIMA TABELA: CHAVES DE USUÁRIO QUE DETERMINAM VISTAS PERMITIDAS NA APP E ROLES EM DBS
-- INSPIRADO EM UM TORNEIO ESPORTIVO

CREATE TABLE profiles (
 endpoint VARCHAR(120) PRIMARY KEY UNIQUE,
 id_usuarios INTEGER NOT NULL,
 avatar_url VARCHAR(200) NOT NULL,
 cover_url VARCHAR(200) NOT NULL,
 FOREIGN KEY (id_usuarios) REFERENCES usuarios(id)
 ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE cargos(
id INTEGER PRIMARY KEY  AUTOINCREMENT UNIQUE,
cargo VARCHAR(120) NOT NULL UNIQUE
);

SELECT * FROM cargos;


INSERT INTO CARGOS (cargo) 
VALUES 
  ("TÉCNICO"),
  ("ASSISTENTE TÉCNICO"),
  ("PREPARADOR FÍSICO"),
  ("ESTATÍSTICO"),
  ("FISIOTERAPEUTA");


SELECT cargo FROM cargos;

CREATE TABLE profile_comissao_tecnica(
   key_comissao_tecnica VARCHAR(120) NOT NULL UNIQUE PRIMARY KEY,
   nome_de_jogo VARCHAR(60) NOT NULL,
   id_roles INTEGER NOT NULL, 
   
);


CREATE TABLE user_keys(
 key_principal VARCHAR(120) PRIMARY KEY,
 key_comissao_tecnica VARCHAR(120) DEFAULT NULL, 
 key_administradores VARCHAR(120) DEFAULT NULL,
 key_staff VARCHAR(120) DEFAULT NULL,
 crm_medico VARCHAR(30) DEFAULT NULL,
 endpoint_profiles VARCHAR(120) NOT NULL,
 FOREIGN KEY (endpoint_profiles) REFERENCE profiles(endpoint)
 ON UPDATE CASCADE ON DELETE CASCADE
);


DROP TABLE user_keys;
CREATE TABLE jogador(
   
);
